<a href="https://colab.research.google.com/github/rakeshmothukuru1/Test/blob/master/TF_Linear_Regression_1.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing

In [3]:
housing = fetch_california_housing()
m,n = housing.data.shape
type(housing)

sklearn.utils.Bunch

In [4]:
type(housing.data)

numpy.ndarray

Adding an Extra Bias Feature. **Question => Why should we add it or how shall we know that we should add a Bias Feature**

In [0]:
housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]

**Question: Why are we considering the variables, X and y as TensorFlow Constants, why not we considering them as TF Variables? **

In [0]:
X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

In [0]:
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)), XT), y)

In [0]:
with tf.Session() as sess:
  theta_value = theta.eval()

**Implementing Gradient Descent:**
    Manually Computing the Gradient Descent

In [0]:
n_epochs = 1000
learning_rate = 0.01

In [0]:
X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

In [0]:
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

In [0]:
init = tf.global_variables_initializer()

In [16]:
with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 ==0:
      print("Epoch", epoch, "MSE =", mse.eval())
    sess.run(training_op)
  best_theta = theta.eval()

Epoch 0 MSE = 1930922.6
Epoch 100 MSE = nan
Epoch 200 MSE = nan
Epoch 300 MSE = nan
Epoch 400 MSE = nan
Epoch 500 MSE = nan
Epoch 600 MSE = nan
Epoch 700 MSE = nan
Epoch 800 MSE = nan
Epoch 900 MSE = nan


**Using Auto Diff:**

In [17]:
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 ==0:
      print("Epoch", epoch, "MSE =", mse.eval())
    sess.run(training_op)
  best_theta = theta.eval()

Epoch 0 MSE = 1954446.6
Epoch 100 MSE = nan
Epoch 200 MSE = nan
Epoch 300 MSE = nan
Epoch 400 MSE = nan
Epoch 500 MSE = nan
Epoch 600 MSE = nan
Epoch 700 MSE = nan
Epoch 800 MSE = nan
Epoch 900 MSE = nan


**Using GradientDescentOptimizer:**

In [18]:
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
#gradients = tf.gradients(mse, [theta])[0]
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
#training_op = tf.assign(theta, theta - learning_rate * gradients)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 ==0:
      print("Epoch", epoch, "MSE =", mse.eval())
    sess.run(training_op)
  best_theta = theta.eval()

Epoch 0 MSE = 739261.56
Epoch 100 MSE = nan
Epoch 200 MSE = nan
Epoch 300 MSE = nan
Epoch 400 MSE = nan
Epoch 500 MSE = nan
Epoch 600 MSE = nan
Epoch 700 MSE = nan
Epoch 800 MSE = nan
Epoch 900 MSE = nan


** Using Momentum Optimizer **

In [19]:
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
#gradients = tf.gradients(mse, [theta])[0]
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
optimizer = tf.train.MomentumOptimizer(learning_rate=learning_rate, momentum=0.9)
#training_op = tf.assign(theta, theta - learning_rate * gradients)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 ==0:
      print("Epoch", epoch, "MSE =", mse.eval())
    sess.run(training_op)
  best_theta = theta.eval()

Epoch 0 MSE = 446015.6
Epoch 100 MSE = nan
Epoch 200 MSE = nan
Epoch 300 MSE = nan
Epoch 400 MSE = nan
Epoch 500 MSE = nan
Epoch 600 MSE = nan
Epoch 700 MSE = nan
Epoch 800 MSE = nan
Epoch 900 MSE = nan


** Feeding the Data to the Training Algorithm: ** Best way to do it is to use Place holder nodes

**Understanding Place Holder Nodes**

In [21]:
A= tf.placeholder(tf.float32, shape = (None, 3))
B = A + 5
with tf.Session() as sess:
  B_Val_1 = B.eval(feed_dict = {A: [[1,2,3]]})
  B_Val_2 = B.eval(feed_dict = {A: [[4,5,6], [7,8,9]]})
  print(B_Val_1)
  print(B_Val_2)

[[6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]]


**Applying it in Mini-Batch Gradient Descent**

In [0]:
X = tf.placeholder(tf.float32, shape = (None, n + 1), name = 'X')
y = tf.placeholder(tf.float32, shape = (None, 1), name = 'y')

**Define the Batch Size and Compute the Total Number of Branches**

In [0]:
batch_size = 100
n_batches = int(np.ceil(m/batch_size))